apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: eureka-server
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: eureka-server
      app.kubernetes.io/component: registry
