apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: eureka

resources:
  - namespace.yaml
  - service-registry.yaml
  - service-peer1.yaml
  - service-peer2.yaml
  - deployment-peer1.yaml
  - deployment-peer2.yaml
  - ingress.yaml
  - pdb.yaml
  - networkpolicy.yaml
