services:
  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - fitness-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/eureka/"]
      interval: 10s
      timeout: 5s
      retries: 10

  api-gateway:
    build: ./API_Gateway
    container_name: api-gateway
    ports:
      - "8075:8075"
    environment:
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka/
    depends_on:
      eureka-server:
        condition: service_healthy
    networks:
      - fitness-network

  trains-service:
    build: ./Trains-Service
    container_name: trains-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      eureka-server:
        condition: service_healthy
    networks:
      - fitness-network

  recommendation-service:
    build: ./Recommendation-Service
    container_name: recommendation-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      eureka-server:
        condition: service_healthy
    networks:
      - fitness-network

  training-service:
    build: ./Training-Servive
    container_name: training-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      eureka-server:
        condition: service_healthy
    networks:
      - fitness-network

    eureka:
      client:
        register-with-eureka: false
        fetch-registry: false
        service-url:
          defaultZone: http://localhost:8761/eureka/

networks:
  fitness-network:
    driver: bridge